version: '3'

services:
  blockplot:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    restart: unless-stopped
    container_name: blockplot-simulator 