version: '3'

services:
  blockplot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8848:8000"
    volumes:
      - ./:/app
    restart: always
    container_name: blockplot-simulator
